#!/bin/bash
#
# Author:   kyo <iprintf@qq.com>
# Date:     2017-01-10 16:54:54
# Location: Shenzhen
# Desc: Use 'log-with-git' to encrypt store.
#

myexit() {
    echo $1
    exit $2
}

vim_last_cmd() {
    local viminfo=~/.viminfo
    test ! -e $viminfo && echo None
    grep -m1 '^:' $viminfo 2> /dev/null
}

log_add() {
    # 临时文件必须不存在，否则视为上次编辑出错
    # 编辑结束, vim最后一条命令为q!、文件不存在或为空代表不保存此文档
    test -e "$tmpfile" && myexit "为什么会存在此文件，请检查!"
    vim $tmpfile
    test ! -e "$tmpfile" && return 0
    filesize=$(wc -c "$tmpfile" | awk '{print $1}')
    test "$filesize" -eq 0 && return 1
    test "$(vim_last_cmd)" == ":q!" && return 1
    title=$(sed -n "1p" $tmpfile)
    cat $tmpfile | $gpg -ae | $recorder add -e -m "$title"
    return 1
}


log_edit() {
    local path=$1 title
    title="Document from file: $path"
    $recorder add -m "$title" < "$path"
}

log_list() {
    echo "list"
}


tmpfile='/tmp/kyo_log_file'
recorder="log -F $HOME/.logtest"
gpg="gpg -r iprintf@qq.com"

log_${1-list} || rm $tmpfile -f
